module.exports = {
    "RECIPE_EN_US" : {
	"work bench": "You can make a Work Bench with 10 Wood by Hand.",
	"furnace": "You can make a Furnace with 20 stone Block, 4 Wood, and 3 Torch next to Work Bench.",
	"iron anvil": "You can make a Iron Anvil with 5 Iron Bar next to Work Bench.",
	"lead anvil": "You can make a Lead Anvil with 5 Lead Bar next to Work Bench.",
	"bottle": "You can make a Bottle with 1 Glass next to Furnace.",
	"sawmill": "You can make a Sawmill with 10 Wood, 2 Iron Bar, and 1 Chain next to Work Bench.",
	"loom": "You can make a Loom with 12 Wood next to Work Bench.",
	"keg": "You can make a Keg with 14 Wood next to Work Bench",
	"cooking pot": "You can make a Cooking Pot with 10 Iron Bar and 2 Wood next to Iron Anvil or Lead Anvil.",
	"hellforge": "Found in the Underworld, needed to make Hellstone Bars.",
	"tinkerers workshop": "Bought from the Goblin Tinkerer, needed to combine Accessories.",
	"dye vat": "Bought from the Dye Trader, needed to make Dyes.",
	"imbuing station": "Bought from the Witch Doctor, needed to make Flasks.",
	"demon altar": "They are found mainly in underground Corruption.",
	"crimson altar": "They are found mainly in Crimson Chasms.",
	"mythril anvil": "You can make a Mythril Anvil with 10 Mythril Bar next to Iron Anvil or Lead Anvil.",
	"orichalcum anvil": "You can make an Orichalcum Anvil with 10 Orichalcum Bar next to Iron Anvil or Lead Anvil.",
	"adamantite forge": "You can make an Adamantite Forge with 30 Adamantite Ore and 1 Hellforge next to Mythril Anvil or Orichalcum Anvil.",
	"titanium forge": "You can make an Titanium Forge with 30 Titanium Ore and 1 Hellforge next to Mythril Anvil or Orichalcum Anvil.",
	"wood": "Wood is a type of block that is generally obtained by cutting down Trees using an Axe or a Chainsaw.",
	"stone block": "Stone Blocks are a type of block that is generally obtained by mining Stone using a Pickaxe.",
	"torch": "You can make 3 Torch with 1 Gel and 1 Wood.",
	"iron bar": "You can make an Iron Bar with 3 Iron Ore next to Furnace.",
	"lead bar": "You can make a Lead Bar with 3 Lead Ore next to Furnace.",
	"glass": "You can make a Glass with 2 Sand Block next to Furnace.",
	"chain": "You can make 10 Chain with 1 Iron Bar or 1 Lead Bar next to Iron Anvil or Lead Anvil",
	"mythril bar": "You can make a Mythril Bar with 3 Mythril Ore next to Furnace.",
	"orichalcum bar": "You can make a Orichalcum Bar with 3 Orichalcum Ore next to Furnace.",
	"adamantite ore": "Adamantite Ores are a type of block that is generally obtained by mining Adamantite using a Pickaxe.",
	"titanium ore": "Titanium Ores are a type of block that is generally obtained by mining Titanium using a Pickaxe.",
	"sand Block": "Sand Blocks are a type of block that is generally obtained by mining Sand using a Pickaxe.",
	"gel": "Gel is a common crafting material dropped by most slimes and Slimed Zombies."
	}
};